name: rms pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get project 
        uses: actions/checkout@v4
      - name: install docker 
        run : sudo apt install -y docker.io
      - name: docker login 
        run:  |
               echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login \
              -u "${{ secrets.DOCKER_USERNAME }}" \
              --password-stdin                                                                                       
      - name: docker-compose
        run:  docker compose up

       
